//
//  DogBreeds.swift
//  DogeWalk
//
//  Created by Katharina Müllek on 14.05.21.
//

import Foundation

struct DogBreeds {
    
    let arrayOfAllBreeds = ["Affenpinscher",
                            "Afghan Hound",
                            "Airedale Terrier",
                            "Akita",
                            "Alaskan Malamute",
                            "American Staffordshire Terrier",
                            "American Water Spaniel",
                            "Australian Cattle Dog",
                            "Australian Shepherd",
                            "Australian Terrier",
                            "Basenji",
                            "Basset Hound",
                            "Beagle",
                            "Bearded Collie",
                            "Bedlington Terrier",
                            "Bernese Mountain Dog",
                            "Bichon Frise",
                            "Black and Tan Coonhound",
                            "Bloodhound", "Border Collie",
                            "Border Terrier", "Borzoi",
                            "Boston Terrier",
                            "Bouvier des Flandres",
                            "Boxer",
                            "Briard",
                            "Brittany",
                            "Brussels Griffon",
                            "Bull Terrier",
                            "Bulldog",
                            "Bullmastiff",
                            "Cairn Terrier",
                            "Canaan Dog",
                            "Chesapeake Bay Retriever",
                            "Chihuahua",
                            "Chinese Crested",
                            "Chow Chow",
                            "Clumber Spaniel",
                            "Cocker Spaniel",
                            "Collie",
                            "Dachshund",
                            "Dalmatian",
                            "Doberman Pinscher",
                            "English Cocker Spaniel",
                            "English Setter",
                            "English Springer Spaniel",
                            "English Toy Spaniel",
                            "Eskimo Dog",
                            "Finnish Spitz",
                            "Fox Terrier",
                            "Foxhound",
                            "French Bulldog",
                            "German Shepherd",
                            "German Shorthaired Pointer",
                            "German Wirehaired Pointer",
                            "Golden Retriever",
                            "Gordon Setter",
                            "Great Dane",
                            "Greyhound",
                            "Irish Setter",
                            "Irish Water Spaniel",
                            "Irish Wolfhound",
                            "Jack Russell Terrier",
                            "Japanese Spaniel",
                            "Keeshond",
                            "Kerry Blue Terrier",
                            "Komondor",
                            "Kuvasz",
                            "Labradoodle",
                            "Labrador Retriever",
                            "Lakeland Terrier",
                            "Lhasa Apso",
                            "Maltese",
                            "Manchester Terrier",
                            "Mastiff",
                            "Mexican Hairless",
                            "Newfoundland",
                            "Norwegian Elkhound",
                            "Norwich Terrier",
                            "Otterhound",
                            "Papillon",
                            "Pekingese",
                            "Pointer",
                            "Pomeranian",
                            "Poodle",
                            "Pug",
                            "Puli",
                            "Rhodesian Ridgeback",
                            "Rottweiler",
                            "Saint Bernard",
                            "Saluki",
                            "Samoyed",
                            "Schipperke",
                            "Schnauzer",
                            "Scottish Deerhound",
                            "Scottish Terrier",
                            "Sealyham Terrier",
                            "Shar-Pei",
                            "Shetland Sheepdog",
                            "Shih Tzu",
                            "Siberian Husky",
                            "Silky Terrier",
                            "Skye Terrier",
                            "Staffordshire Bull Terrier",
                            "Wheaten Terrier",
                            "Sussex Spaniel",
                            "Spitz",
                            "Tibetan Terrier",
                            "Vizsla",
                            "Weimaraner",
                            "Welsh Corgi",
                            "Welsh Terrier",
                            "West Highland White Terrier",
                            "Whippet",
                            "Yorkshire Terrier"]
    
}
